### ISSUE TITLE
3.5.5 clusterservice.yaml

### ISSUE THREAD

**Issue by EmmaHumber** [IBM/ibm-common-service-operator#254]
Jiaming asked me to raise this issue:

Can the 3.5.5 equivalent of this file be created please? https://github.com/IBM/ibm-common-service-operator/blob/master/deploy/olm-catalog/ibm-common-service-operator/3.5.4/ibm-common-service-operator.v3.5.4.clusterserviceversion.yaml

We would like to add the Events Operator stanza to the csOperandRegistry.spec.operators stanza, but it's not due out in 3.5.4 so I can't add it until the 3.5.5 file exists:

```
        - name: ibm-events-operator
          namespace: ibm-common-services
          channel: beta
          packageName: ibm-events-operator
          scope: public
          sourceName: opencloud-operators
          sourceNamespace: openshift-marketplace
```

**Comment by horis233** [comment]
Thanks @EmmaHumber, I will create a PR for this change when we bump to 3.5.5 today.

**Comment by EmmaHumber** [comment]
Hi @horis233 - I was mistaken when i said the Events Operator should be added to common services 3.5.5.

That release is only to add OCP 4.6 support.

The Events Operator should be added to the 3.6 release of common services

I've created a PR to undo your change - https://github.com/IBM/ibm-common-service-operator/pull/257
