### ISSUE TITLE
Many other operators being installed when installing ODLM

### ISSUE THREAD

**Issue by sruthakeerthikotla** [IBM/ibm-common-service-operator#255]
Hello!

I installed the latest version 3.5.4 of common services from Operator Hub. Previously ODLM was installed automatically but now that does not seem to happen. When I do install ODLM from operator hub explicitly, there are 10 other operators being installed(like MongoDB, Helm, UI etc etc). Is this a bug or is this expected? I personally don't need all these operators installed and hence it would be great if only the required ODLM ca be installed.

Thank you,
Srutha K

**Comment by horis233** [comment]
Hi @sruthakeerthikotla, Is it a fresh installation? ODLM should be installed by the common service operator automatically.
 If only ODLM and common service operator are deployed without any OperandRequest, these operators wouldn't suppose to be deployed.

**Comment by sruthakeerthikotla** [comment]
@horis233 , I tried the installation in a new cluster and everything works as expected. Sorry for the issue. It is a false alarm. Closing it!
