### ISSUE TITLE
Add Redis operator to ODLM

### ISSUE THREAD

**Issue by ericabr** [IBM/ibm-common-service-operator#315]
For 1Q we need to add the redis operator here: https://github.ibm.com/CloudPakOpenContent/redis-operator
to ODLM.

**Comment by ericabr** [comment]
When will we get this into ODLM?

**Comment by horis233** [comment]
@Daniel-Fan Could you please create a PR to onboard redis operator? Redis operator is from the ibm-catalog.

**Comment by Daniel-Fan** [comment]
The PR was created
https://github.com/IBM/ibm-common-service-operator/pull/353

**Comment by horis233** [comment]
PR is merged, closing the issue
