### ISSUE TITLE
Unable to delete commonservice CR due to the existence of finalizer

### ISSUE THREAD

**Issue by Daniel-Fan** [IBM/ibm-common-service-operator#343]
When I try to uninstall the Common Service, the CR commonservice in cs-operator cannot be deleted because there exists finalizer.

Need to use patching to remove finalizer

/cc @horis233

**Comment by horis233** [comment]
The finalizer is added for updating the size from the OperandConfig when the common service CR is deleted.

We can think of another way to avoid using the `finalizer`.

For example, if the instance from the request can't be found, the update the size from the OperandConfig by others OperandRequests.
