### ISSUE TITLE
One of the pods icp-mongodb-2 is stuck in Init:1/2 state.

### ISSUE THREAD

**Issue by sachinjha** [IBM/ibm-common-service-operator#387]
This is happening in a CP4I 2020.3.1 instance setup on ROKS 4.4 for a partner in IBM Cloud.  It was running fine until the certificates expired. After regeneration of the certificates the ipc-mongdb-2 pod is stuck in this state. The bootstrap (init)container is still Running but no obvious errors in the log.  PV, PVC and POD do not have any error events and PV is attached and accessible from the bootstrap pod.

**bootstrap container logs:**
Sachins-MacBook-Pro-2:~ sachinkumarjha$ oc logs icp-mongodb-2 -c bootstrap
2021/01/28 06:05:38 Determined Domain to be ibm-common-services.svc.cluster.local
2021/01/28 06:05:38 Peer list updated
was []
now [icp-mongodb-0.icp-mongodb.ibm-common-services.svc.cluster.local icp-mongodb-1.icp-mongodb.ibm-common-services.svc.cluster.local icp-mongodb-2.icp-mongodb.ibm-common-services.svc.cluster.local]
2021/01/28 06:05:38 execing: /init/on-start.sh with stdin: icp-mongodb-0.icp-mongodb.ibm-common-services.svc.cluster.local
icp-mongodb-1.icp-mongodb.ibm-common-services.svc.cluster.local
icp-mongodb-2.icp-mongodb.ibm-common-services.svc.cluster.local

**Describe Pod :**

Sachins-MacBook-Pro-2:~ sachinkumarjha$ oc describe pod icp-mongodb-2
Name:         icp-mongodb-2
Namespace:    ibm-common-services
Priority:     0
Node:         10.73.236.67/10.73.236.67
Start Time:   Thu, 28 Jan 2021 11:35:25 +0530
Labels:       app=icp-mongodb
              app.kubernetes.io/instance=common-mongodb
              controller-revision-hash=icp-mongodb-86bb8c788
              release=mongodb
              statefulset.kubernetes.io/pod-name=icp-mongodb-2
Annotations:  clusterhealth.ibm.com/dependencies: ibm-common-services.cert-manager
              cni.projectcalico.org/podIP: 172.30.209.174/32
              cni.projectcalico.org/podIPs: 172.30.209.174/32
              cs-podpreset.operator.ibm.com/podpreset-ibm-common-service-webhook: 83674
              k8s.v1.cni.cncf.io/networks-status:
                [{
                    "name": "k8s-pod-network",
                    "ips": [
                        "172.30.209.174"
                    ],
                    "dns": {}
                }]
              openshift.io/scc: restricted
              productID: 068a62892a1e4db39641342e592daa25
              productMetric: FREE
              productName: IBM Cloud Platform Common Services
              prometheus.io/path: /metrics
              prometheus.io/port: 9216
              prometheus.io/scrape: true
Status:       Pending
IP:           172.30.209.174
IPs:
  IP:           172.30.209.174
Controlled By:  StatefulSet/icp-mongodb
Init Containers:
  install:
    Container ID:  cri-o://9e7886c77c716bc1de2acc9a785a7d0f6684202f747acbd0869963f6ddce90ff
    Image:         quay.io/opencloudio/ibm-mongodb-install@sha256:1211ee8ece2791b91fadd5b1294749e46cb88cef5f3a37e1d9dd6890038f1043
    Image ID:      quay.io/opencloudio/ibm-mongodb-install@sha256:1211ee8ece2791b91fadd5b1294749e46cb88cef5f3a37e1d9dd6890038f1043
    Port:          <none>
    Host Port:     <none>
    Command:
      /install/install.sh
    Args:
      --work-dir=/work-dir
      --config-dir=/data/configdb
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 28 Jan 2021 11:35:36 +0530
      Finished:     Thu, 28 Jan 2021 11:35:36 +0530
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  2Gi
    Requests:
      cpu:        2
      memory:     2Gi
    Environment:  <none>
    Mounts:
      /ca-readonly from ca (rw)
      /configdb-readonly from config (rw)
      /data/configdb from configdir (rw)
      /data/db from mongodbdir (rw,path="datadir")
      /install from install (rw)
      /keydir-readonly from keydir (rw)
      /tmp from tmp-mongodb (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from ibm-mongodb-operand-token-4887s (ro)
      /work-dir from mongodbdir (rw,path="workdir")
  bootstrap:
    Container ID:  cri-o://b41088c8b31092d3d7e4273537dd4511cd2735d45b2b8b3a8274038d1849599b
    Image:         quay.io/opencloudio/ibm-mongodb@sha256:5004b6073efd2df5eae51431e866123d386495aea1b4baa2dcac9fcbaaf7eb83
    Image ID:      quay.io/opencloudio/ibm-mongodb@sha256:5004b6073efd2df5eae51431e866123d386495aea1b4baa2dcac9fcbaaf7eb83
    Port:          <none>
    Host Port:     <none>
    Command:
      /work-dir/peer-finder
    Args:
      -on-start=/init/on-start.sh
      -service=icp-mongodb
    State:          Running
      Started:      Thu, 28 Jan 2021 11:35:38 +0530
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  2Gi
    Requests:
      cpu:     2
      memory:  2Gi
    Environment:
      POD_NAMESPACE:       ibm-common-services (v1:metadata.namespace)
      REPLICA_SET:         rs0
      AUTH:                true
      ADMIN_USER:          <set to the key 'user' in secret 'icp-mongodb-admin'>      Optional: false
      ADMIN_PASSWORD:      <set to the key 'password' in secret 'icp-mongodb-admin'>  Optional: false
      METRICS:             true
      METRICS_USER:        <set to the key 'user' in secret 'icp-mongodb-metrics'>      Optional: false
      METRICS_PASSWORD:    <set to the key 'password' in secret 'icp-mongodb-metrics'>  Optional: false
      NETWORK_IP_VERSION:  ipv4
    Mounts:
      /data/configdb from configdir (rw)
      /data/db from mongodbdir (rw,path="datadir")
      /init from init (rw)
      /tmp from tmp-mongodb (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from ibm-mongodb-operand-token-4887s (ro)
      /work-dir from mongodbdir (rw,path="workdir")
Containers:
  icp-mongodb:
    Container ID:  
    Image:         quay.io/opencloudio/ibm-mongodb@sha256:5004b6073efd2df5eae51431e866123d386495aea1b4baa2dcac9fcbaaf7eb83
    Image ID:      
    Port:          27017/TCP
    Host Port:     0/TCP
    Command:
      mongod
      --config=/data/configdb/mongod.conf
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  2Gi
    Requests:
      cpu:      2
      memory:   2Gi
    Liveness:   exec [mongo --ssl --sslCAFile=/data/configdb/tls.crt --sslPEMKeyFile=/work-dir/mongo.pem --eval db.adminCommand('ping')] delay=30s timeout=10s period=30s #success=1 #failure=5
    Readiness:  exec [mongo --ssl --sslCAFile=/data/configdb/tls.crt --sslPEMKeyFile=/work-dir/mongo.pem --eval db.adminCommand('ping')] delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment:
      AUTH:            true
      ADMIN_USER:      <set to the key 'user' in secret 'icp-mongodb-admin'>      Optional: false
      ADMIN_PASSWORD:  <set to the key 'password' in secret 'icp-mongodb-admin'>  Optional: false
    Mounts:
      /data/configdb from configdir (rw)
      /data/db from mongodbdir (rw,path="datadir")
      /tmp from tmp-mongodb (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from ibm-mongodb-operand-token-4887s (ro)
      /work-dir from mongodbdir (rw,path="workdir")
  metrics:
    Container ID:  
    Image:         quay.io/opencloudio/ibm-mongodb-exporter@sha256:d919b68e11254c38bef86b036ce5636e62699045d22c04c3c7ce616d95f341ec
    Image ID:      
    Port:          9216/TCP
    Host Port:     0/TCP
    Command:
      sh
      -ec
      /bin/mongodb_exporter --mongodb.uri mongodb://$METRICS_USER:$METRICS_PASSWORD@localhost:27017 --mongodb.tls --mongodb.tls-ca=/data/configdb/tls.crt --mongodb.tls-cert=/work-dir/mongo.pem --mongodb.socket-timeout=3s --mongodb.sync-timeout=1m --web.telemetry-path=/metrics --web.listen-address=:9216
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  350Mi
    Requests:
      cpu:      100m
      memory:   300Mi
    Liveness:   exec [sh -ec /bin/mongodb_exporter --mongodb.uri mongodb://$METRICS_USER:$METRICS_PASSWORD@localhost:27017 --mongodb.tls --mongodb.tls-ca=/data/configdb/tls.crt --mongodb.tls-cert=/work-dir/mongo.pem --test] delay=30s timeout=10s period=30s #success=1 #failure=10
    Readiness:  exec [sh -ec /bin/mongodb_exporter --mongodb.uri mongodb://$METRICS_USER:$METRICS_PASSWORD@localhost:27017 --mongodb.tls --mongodb.tls-ca=/data/configdb/tls.crt --mongodb.tls-cert=/work-dir/mongo.pem --test] delay=30s timeout=1s period=10s #success=1 #failure=3
    Environment:
      METRICS_USER:      <set to the key 'user' in secret 'icp-mongodb-metrics'>      Optional: false
      METRICS_PASSWORD:  <set to the key 'password' in secret 'icp-mongodb-metrics'>  Optional: false
    Mounts:
      /data/configdb from configdir (rw)
      /tmp from tmp-metrics (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from ibm-mongodb-operand-token-4887s (ro)
      /work-dir from mongodbdir (rw,path="workdir")
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  mongodbdir:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  mongodbdir-icp-mongodb-2
    ReadOnly:   false
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      icp-mongodb
    Optional:  false
  init:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      icp-mongodb-init
    Optional:  false
  install:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      icp-mongodb-install
    Optional:  false
  ca:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  mongodb-root-ca-cert
    Optional:    false
  keydir:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  icp-mongodb-keyfile
    Optional:    false
  configdir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  tmp-mongodb:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  tmp-metrics:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  ibm-mongodb-operand-token-4887s:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ibm-mongodb-operand-token-4887s
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly
                 dedicated:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/unreachable:NoExecute
Events:
  Type    Reason     Age        From                   Message
  ----    ------     ----       ----                   -------
  Normal  Scheduled  <unknown>  default-scheduler      Successfully assigned ibm-common-services/icp-mongodb-2 to 10.73.236.67
  Normal  Pulled     75m        kubelet, 10.73.236.67  Container image "quay.io/opencloudio/ibm-mongodb-install@sha256:1211ee8ece2791b91fadd5b1294749e46cb88cef5f3a37e1d9dd6890038f1043" already present on machine
  Normal  Created    75m        kubelet, 10.73.236.67  Created container install
  Normal  Started    75m        kubelet, 10.73.236.67  Started container install
  Normal  Pulled     75m        kubelet, 10.73.236.67  Container image "quay.io/opencloudio/ibm-mongodb@sha256:5004b6073efd2df5eae51431e866123d386495aea1b4baa2dcac9fcbaaf7eb83" already present on machine
  Normal  Created    75m        kubelet, 10.73.236.67  Created container bootstrap
  Normal  Started    75m        kubelet, 10.73.236.67  Started container bootstrap
Sachins-MacBook-Pro-2:~ sachinkumarjha$

**Comment by pgodowski** [comment]
please open this ticket in the corresponding internal repo where the customer issues are tracked and discusses. thanks.
