### ISSUE TITLE
Allow users of ODLM to specify OLM dependencies for the APIs

### ISSUE THREAD

**Issue by taylormgeorge91** [IBM/ibm-common-service-operator#434]
## Summary

Today the `ibm-common-service-operator` bootstraps the `operand-lifecycle-operator-manager` as well as a supporting `namespacescope` operator, among other bootstrapping tasks.

It is told that the users of ODLM must include `ibm-common-service-operator` and must not include ODLM in their definitions.

This request is to allow the users of ODLM to declare their API and package requirements through OLM.

## Details

There are at least two other operators who have adopted ODLM for their deployment architecture:
- ibm-management-orchestrator
- ibm-aiops-orchestrator

These operators include the ODLM golang library and directly interface with the ODLM APIs in kubernetes.
The deployment architecture for the operands of these operators is based on ODLM as a fundamental component. 
If the ODLM APIs do not exist, or are not within the supported range, the operators will panic.

Further, these operators are not yet offered through a `bundle` format in OLM. What this means is that they are only specifying required APIs in the CSV and are *not* utilizing the bundle `dependencies.yaml` for GVK and package type specifications.

**Comment by horis233** [comment]
@taylormgeorge91 

ibm-common-service-operator also gets and updates OperandConfig and OperandRegistry. Currently, we use api.Reader to avoid panic.

I believe we can't use `customresourcedefinitions.required` to explicitly claim the dependency since OLM will deploy an ODLM in the namespace of the operator, which is not expected.

Do you know if there is any mechanism from OLM to handle the operator in the `pending` status until the required CRD exists instead of just creating it?

**Comment by taylormgeorge91** [comment]
@horis233 That is a good point but not something I think OLM supports
>Do you know if there is any mechanism from OLM to handle the operator in the pending status until the required CRD exists instead of just creating it?

I can ask the OLM guild and see if that is of any consideration.

We could create an init container to validate, but we would really like to use the OLM dependency management for required APIs as that is the accepted norm.

I will get a log of the error.

**Comment by horis233** [comment]
@taylormgeorge91 

Please check if the nativeAPI field in the CSV can fulfill the requirement. 
https://olm.operatorframework.io/docs/tasks/creating-operator-manifests/#nativeapis-recommended

**Comment by taylormgeorge91** [comment]
Thanks @horis233 ! I'll give it a go, looks like what we want.

**Comment by taylormgeorge91** [comment]
Works well, thanks again.
